name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn nx format:check

      - run: yarn nx affected --target=lint --parallel=3 --all

      - run: yarn nx affected --target=build --parallel=3 --all

      - run: yarn nx affected --target=test --parallel=2 --all

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/libs/query-angular/clover.xml,./coverage/libs/query-core/clover.xml

      - name: Create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          commit: 'chore: 🤖 update versions'
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn nx format:check

      - run: yarn nx affected --target=lint --parallel=3

      - run: yarn nx affected --target=build --parallel=3

      - run: yarn nx affected --target=test --parallel=2
